### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by v6r** [nelleu/Replit-Scraper#1]
Hi,
If i try to run with: go build -ldflags "-s -w following message pop up:

D:\Downloads\Replit-Scraper-main>go build -ldflags "-s -w
go: go.mod file not found in current directory or any parent directory; see 'go help modules'

If i try to run: go run main.go following message pop up:

D:\Downloads\Replit-Scraper-main>go run main.go
main.go:20:7: no required module provides package github.com/gookit/color: go.mod file not found in current directory or any parent directory; see 'go help modules'

**Comment by bytixo** [comment]
```bash
go mod init learngolang
go mod tidy
go build -ldflags "-s -w" && learngolang.exe
```

**Comment by v6r** [comment]
> ```shell
> go mod init learngolang
> go mod tidy
> go build -ldflags "-s -w" && learngolang.exe
> ```

Ty, this worked but noe i have a new Error:

D:\Downloads\Replit-Scraper-main>go build -ldflags "-s -w" && learngolang.exe
# learngolang
.\main.go:99:17: cannot refer to unexported name exec.command
.\main.go:130:17: syntax error: mixed named and unnamed function parameters

**Comment by bytixo** [comment]
Code is shit here fixed: https://gist.github.com/bytixo/4e3073e0fcfcb5be3d490b492afd80a6

**Comment by nelleu** [comment]
lol I said in the code itself the code was bad, I'm not the best at golang but I'm learning so I'll make sure to do better next time

**Comment by bytixo** [comment]
i mean itself its good, its just that there was a lot of typos in the variable names and function args

**Comment by nelleu** [comment]
ah thanks for letting me know, i didnt test it very well when i was finished but ill make sure to do that next time
